### ISSUE TITLE
How to achieved such a good result?

### ISSUE THREAD

**Issue by benjaminlinken** [DaFun/Image-Enhancement#1]
Hi @DaFun,
I was studying hdrnet recently, but I had some problems.Did you retrained the network or using pretrained model? Can you tell me how you achieved such a good result?
Any feedback is highly appreciated.

**Comment by DaFun** [comment]
I used the pretrained model. Maybe you can try to run it on the desktop first.

**Comment by benjaminlinken** [comment]
@DaFun I also use the pretrained model,but the picture turns green.Do you know what is the "specially formatted 16-bit linear input" ?

**Comment by benjaminlinken** [comment]
@DaFun How do you avoid weird color of the output？

**Comment by DaFun** [comment]
Yes, those guys used special formatted pics to train the hdr model. But as far as I know, they open sourced those hdrplus data recently. So maybe it's able to retrain it now.

**Comment by benjaminlinken** [comment]
@DaFun Would you mind telling me which type of picture do you use as input to avoid weird color ?

**Comment by benjaminlinken** [comment]
@DaFun I have been retrain the network, but the result is not as good as they mentioned in the paper.

**Comment by benjaminlinken** [comment]
@DaFun Do you convert RGB images to yuv images as input?

**Comment by benjaminlinken** [comment]
@DaFun 
Please reply me ?

thank you very much

**Comment by DaFun** [comment]
@benjaminlinken  Can you try to adjust the white balance of photos? Besides, there is a clue in their code - 'if im_input.dtype == np.uint16 and args.hdrp' in run.py.
By the way, the example I show in the github is from the edge-aware model, not from the hdrp model. 
Good luck.
